- name: Install Apache
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2
    - libapache2-mod-php5
  tags: apache

- name: "Clear config 'other-vhosts-access-log.conf'"
  shell: cp /dev/null /etc/apache2/conf.d/other-vhosts-access-log
  tags: apache

- name: Configure Apache
  template: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
    - restart apache
  tags: apache

- name: Configure Apache Virtual hosts
  template: src=app.conf dest=/etc/apache2/sites-available/{{ item.name }}
  with_items: '{{vhosts}}'
  notify:
    - restart apache
  tags: apache

- name: Enable apache modules
  shell: a2enmod {{ item }}
  with_items:
    - rewrite
    - php5
  notify:
    - restart apache
  tags: apache

- name: Disable default config
  file: path={{ item }} state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default
    - /etc/apache2/sites-available/default
  notify:
    - restart apache
  tags: apache

- name: Enable config sites
  file: src=/etc/apache2/sites-available/{{ item.name }} dest=/etc/apache2/sites-enabled/{{ item.name }} state=link
  with_items: '{{vhosts}}'
  notify:
    - restart apache
  tags: apache