#- name: Installing composer dependencies
#  composer: command=install working_dir={{ root_dir }} prefer_dist=yes no_dev=yes
#  tags: demo
#
#- name: Installing bower dependencies
#  shell: bower install --allow-root -F chdir={{ root_dir }}
#  tags: demo

- name: Chown project
  file: path={{ root_dir }} state=directory owner={{ username }} group={{ username }}
  tags: demo